# Generated by Django 5.2.17 on 2026-08-22 21:53

import apps.galleries.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('ARCHIVED', 'Archivada')], db_index=True, default='DRAFT', max_length=12)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE_PIN', 'Privada con PIN'), ('UNLISTED', 'No listada')], db_index=True, default='PUBLIC', max_length=12)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('allow_photo_download', models.BooleanField(default=False)),
                ('allow_gallery_download', models.BooleanField(default=False)),
                ('show_in_portfolio', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'galería',
                'verbose_name_plural': 'galerías',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_file', models.FileField(upload_to=apps.galleries.models.gallery_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('orientation', models.CharField(choices=[('LANDSCAPE', 'Horizontal'), ('PORTRAIT', 'Vertical'), ('SQUARE', 'Cuadrada'), ('UNKNOWN', 'Desconocida')], default='UNKNOWN', max_length=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('READY', 'Lista'), ('ERROR', 'Error')], default='PENDING', max_length=12)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fotografía',
                'verbose_name_plural': 'fotografías',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_galleries', to='galleries.photo'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['gallery', 'sort_order'], name='galleries_p_gallery_ba1805_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='photo_sort_order_nonnegative'),
        ),
    ]
