# Generated by Django 5.2.17 on 2026-08-22 22:02

import apps.galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='optimized_file',
            field=models.FileField(blank=True, upload_to=apps.galleries.models.optimized_upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='processing_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to=apps.galleries.models.thumbnail_upload_path),
        ),
    ]
