# Generated by Django 5.2.17 on 2026-08-23 00:50

import apps.galleries.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_photo_optimized_file_photo_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('READY', 'Lista'), ('ERROR', 'Error'), ('EXPIRED', 'Expirada')], db_index=True, default='PENDING', max_length=12)),
                ('file', models.FileField(blank=True, upload_to=apps.galleries.models.gallery_download_upload_path)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('processed_photos', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('authorization_hash', models.CharField(db_index=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='galleries.gallery')),
            ],
            options={
                'verbose_name': 'descarga de galería',
                'verbose_name_plural': 'descargas de galerías',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['gallery', 'status', 'expires_at'], name='galleries_g_gallery_26e105_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('processed_photos__lte', models.F('photo_count'))), name='gallery_download_progress_lte_total'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING', 'READY'])), fields=('gallery', 'content_fingerprint', 'authorization_hash'), name='unique_active_gallery_download')],
            },
        ),
    ]
