# Generated by Django 5.2.17 on 2026-08-23 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_gallerydownload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Creada'), ('UPLOADING', 'Subiendo'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('PARTIAL', 'Parcial'), ('ABORTED', 'Abortada'), ('EXPIRED', 'Expirada'), ('ERROR', 'Error')], db_index=True, default='CREATED', max_length=12)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('completed_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_upload_batches', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='galleries.gallery')),
            ],
            options={
                'verbose_name': 'lote de carga',
                'verbose_name_plural': 'lotes de carga',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reserved_photo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=700, unique=True)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('last_modified', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Esperando'), ('UPLOADING', 'Subiendo'), ('UPLOADED', 'Subida completa'), ('CONFIRMED', 'Confirmada'), ('PROCESSING', 'Procesando'), ('READY', 'Lista'), ('ERROR', 'Error'), ('ABORTED', 'Abortada'), ('EXPIRED', 'Expirada')], db_index=True, default='PENDING', max_length=12)),
                ('upload_mode', models.CharField(choices=[('SINGLE', 'PUT único'), ('MULTIPART', 'Multipart')], max_length=12)),
                ('multipart_upload_id', models.CharField(blank=True, max_length=1024)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='galleries.galleryuploadbatch')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_items', to='galleries.gallery')),
                ('photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_upload_item', to='galleries.photo')),
            ],
            options={
                'verbose_name': 'archivo de carga',
                'verbose_name_plural': 'archivos de carga',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='galleryuploadbatch',
            index=models.Index(fields=['gallery', 'created_by', 'status'], name='galleries_g_gallery_f21555_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryuploaditem',
            index=models.Index(fields=['batch', 'status'], name='galleries_g_batch_i_cf2f2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='galleryuploaditem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_size__gt', 0)), name='gallery_upload_item_size_positive'),
        ),
    ]
