# Generated by Django 5.2.17 on 2026-08-23 02:33

import apps.galleries.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_galleryuploadbatch_galleryuploaditem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='allow_gallery_download',
            field=models.BooleanField(default=False, verbose_name='permitir descarga completa'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='allow_photo_download',
            field=models.BooleanField(default=False, verbose_name='permitir descarga individual'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_galleries', to='galleries.photo', verbose_name='fotografía de portada'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_galleries', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha del evento'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='galería destacada'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='protección del PIN'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicada'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='show_in_portfolio',
            field=models.BooleanField(default=False, verbose_name='mostrar en el portafolio'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='identificador web'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('ARCHIVED', 'Archivada')], db_index=True, default='DRAFT', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE_PIN', 'Privada con PIN'), ('UNLISTED', 'No listada')], db_index=True, default='PUBLIC', max_length=12, verbose_name='visibilidad'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='authorization_hash',
            field=models.CharField(db_index=True, max_length=64, verbose_name='huella de autorización'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completada'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='content_fingerprint',
            field=models.CharField(db_index=True, max_length=64, verbose_name='huella del contenido'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='error',
            field=models.CharField(blank=True, max_length=500, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expira'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.galleries.models.gallery_download_upload_path, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='tamaño'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='photo_count',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad de fotografías'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='processed_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías procesadas'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='solicitada'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='iniciada'),
        ),
        migrations.AlterField(
            model_name='gallerydownload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('READY', 'Lista'), ('ERROR', 'Error'), ('EXPIRED', 'Expirada')], db_index=True, default='PENDING', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='completed_files',
            field=models.PositiveIntegerField(default=0, verbose_name='archivos completados'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_upload_batches', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='expira'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='failed_files',
            field=models.PositiveIntegerField(default=0, verbose_name='archivos con error'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creada'), ('UPLOADING', 'Subiendo'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('PARTIAL', 'Parcial'), ('ABORTED', 'Abortada'), ('EXPIRED', 'Expirada'), ('ERROR', 'Error')], db_index=True, default='CREATED', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='total_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='tamaño total'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='total_files',
            field=models.PositiveIntegerField(default=0, verbose_name='archivos totales'),
        ),
        migrations.AlterField(
            model_name='galleryuploadbatch',
            name='uploaded_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='tamaño subido'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='galleries.galleryuploadbatch', verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completado'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='content_type',
            field=models.CharField(max_length=100, verbose_name='tipo de contenido'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='error',
            field=models.CharField(blank=True, max_length=500, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='expected_size',
            field=models.PositiveBigIntegerField(verbose_name='tamaño esperado'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='expira'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_items', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='last_modified',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='última modificación'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='multipart_upload_id',
            field=models.CharField(blank=True, max_length=1024, verbose_name='identificador de carga por partes'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='object_key',
            field=models.CharField(max_length=700, unique=True, verbose_name='clave del objeto'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='nombre original'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_upload_item', to='galleries.photo', verbose_name='fotografía'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='reserved_photo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador reservado'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Esperando'), ('UPLOADING', 'Subiendo'), ('UPLOADED', 'Subida completa'), ('CONFIRMED', 'Confirmada'), ('PROCESSING', 'Procesando'), ('READY', 'Lista'), ('ERROR', 'Error'), ('ABORTED', 'Abortada'), ('EXPIRED', 'Expirada')], db_index=True, default='PENDING', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='galleryuploaditem',
            name='upload_mode',
            field=models.CharField(choices=[('SINGLE', 'Carga única'), ('MULTIPART', 'Carga por partes')], max_length=12, verbose_name='modo de carga'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='tamaño'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='alto'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='tipo de contenido'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='optimized_file',
            field=models.FileField(blank=True, upload_to=apps.galleries.models.optimized_upload_path, verbose_name='archivo optimizado'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='orientation',
            field=models.CharField(choices=[('LANDSCAPE', 'Horizontal'), ('PORTRAIT', 'Vertical'), ('SQUARE', 'Cuadrada'), ('UNKNOWN', 'Desconocida')], default='UNKNOWN', max_length=12, verbose_name='orientación'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original_file',
            field=models.FileField(upload_to=apps.galleries.models.gallery_upload_path, verbose_name='archivo original'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='nombre original'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='procesada'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='processing_error',
            field=models.CharField(blank=True, max_length=500, verbose_name='error de procesamiento'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('READY', 'Lista'), ('ERROR', 'Error')], default='PENDING', max_length=12, verbose_name='estado de procesamiento'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to=apps.galleries.models.thumbnail_upload_path, verbose_name='miniatura'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='subida por'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ancho'),
        ),
    ]
