# Generated by Django 5.2.17 on 2026-08-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al panel administrativo.', verbose_name='acceso al panel administrativo'),
        ),
    ]
