# Generated by Django 5.2.17 on 2026-08-22 23:30

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0002_photo_optimized_file_photo_processed_at_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='GalleryAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('enabled', models.BooleanField(default=False)),
                ('face_search_enabled', models.BooleanField(default=False)),
                ('indexing_status', models.CharField(choices=[('DISABLED', 'Desactivado'), ('PENDING', 'Preparando'), ('INDEXING', 'Indexando'), ('READY', 'Listo'), ('ERROR', 'Error')], db_index=True, default='DISABLED', max_length=12)),
                ('indexed_photos', models.PositiveIntegerField(default=0)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='galleries.gallery')),
            ],
            options={
                'verbose_name': 'configuración de Mapache AI',
                'verbose_name_plural': 'configuraciones de Mapache AI',
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('face_index', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=128)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='galleries.gallery')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='galleries.photo')),
            ],
            options={
                'verbose_name': 'embedding facial',
                'verbose_name_plural': 'embeddings faciales',
                'indexes': [models.Index(fields=['gallery', 'photo'], name='mapache_ai__gallery_723894_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='face_embedding_cos_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('photo', 'face_index'), name='unique_face_index_per_photo'), models.CheckConstraint(condition=models.Q(('face_index__gte', 0)), name='face_index_nonnegative'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='face_confidence_range')],
            },
        ),
        migrations.CreateModel(
            name='FaceSearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_version', models.CharField(max_length=20)),
                ('consented_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('ERROR', 'Error')], max_length=12)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_search_sessions', to='galleries.gallery')),
            ],
            options={
                'verbose_name': 'sesión de búsqueda facial',
                'verbose_name_plural': 'sesiones de búsqueda facial',
                'indexes': [models.Index(fields=['gallery', 'expires_at'], name='mapache_ai__gallery_3645bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhotoFaceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('INDEXING', 'Indexando'), ('READY', 'Lista'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=12)),
                ('face_count', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_face_indexes', to='galleries.gallery')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_index_state', to='galleries.photo')),
            ],
            options={
                'verbose_name': 'estado de índice facial',
                'verbose_name_plural': 'estados de índice facial',
                'indexes': [models.Index(fields=['gallery', 'status'], name='mapache_ai__gallery_dbf824_idx')],
            },
        ),
    ]
