# Generated by Django 5.2.17 on 2026-08-22 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_legacy_face_progress(apps, schema_editor):
    GalleryAISettings = apps.get_model("mapache_ai", "GalleryAISettings")
    for record in GalleryAISettings.objects.all().iterator():
        record.face_indexing_status = record.indexing_status
        record.face_indexed_photos = record.indexed_photos
        record.face_total_photos = record.total_photos
        record.face_last_indexed_at = record.last_indexed_at
        record.save(
            update_fields=[
                "face_indexing_status",
                "face_indexed_photos",
                "face_total_photos",
                "face_last_indexed_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_photo_optimized_file_photo_processed_at_and_more'),
        ('mapache_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibPhotoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('INDEXING', 'Indexando'), ('READY', 'Lista'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=12)),
                ('detected_count', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'análisis de dorsales',
                'verbose_name_plural': 'análisis de dorsales',
            },
        ),
        migrations.CreateModel(
            name='BibSearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('normalized_number', models.CharField(max_length=16)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('raw_text', models.CharField(max_length=64)),
                ('normalized_number', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dorsal detectado',
                'verbose_name_plural': 'dorsales detectados',
            },
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_format',
            field=models.CharField(choices=[('NUMERIC', 'Numérico'), ('ALPHANUMERIC', 'Alfanumérico')], default='NUMERIC', max_length=16),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_indexed_photos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_indexing_status',
            field=models.CharField(choices=[('DISABLED', 'Desactivado'), ('PENDING', 'Preparando'), ('INDEXING', 'Indexando'), ('READY', 'Listo'), ('ERROR', 'Error')], db_index=True, default='DISABLED', max_length=12),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_last_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_max_length',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_min_length',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_search_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='bib_total_photos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='face_indexed_photos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='face_indexing_status',
            field=models.CharField(choices=[('DISABLED', 'Desactivado'), ('PENDING', 'Preparando'), ('INDEXING', 'Indexando'), ('READY', 'Listo'), ('ERROR', 'Error')], db_index=True, default='DISABLED', max_length=12),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='face_last_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryaisettings',
            name='face_total_photos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(copy_legacy_face_progress, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='galleryaisettings',
            constraint=models.CheckConstraint(condition=models.Q(('bib_min_length__gte', 1)), name='bib_min_length_positive'),
        ),
        migrations.AddConstraint(
            model_name='galleryaisettings',
            constraint=models.CheckConstraint(condition=models.Q(('bib_max_length__gte', models.F('bib_min_length'))), name='bib_length_range_valid'),
        ),
        migrations.AddField(
            model_name='bibphotoanalysis',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_photo_analyses', to='galleries.gallery'),
        ),
        migrations.AddField(
            model_name='bibphotoanalysis',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bib_analysis_state', to='galleries.photo'),
        ),
        migrations.AddField(
            model_name='bibsearchsession',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_search_sessions', to='galleries.gallery'),
        ),
        migrations.AddField(
            model_name='detectedbib',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_bibs', to='galleries.gallery'),
        ),
        migrations.AddField(
            model_name='detectedbib',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_bibs', to='galleries.photo'),
        ),
        migrations.AddIndex(
            model_name='bibphotoanalysis',
            index=models.Index(fields=['gallery', 'status'], name='bib_analysis_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bibsearchsession',
            index=models.Index(fields=['gallery', 'expires_at'], name='bib_session_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedbib',
            index=models.Index(fields=['gallery', 'normalized_number'], name='bib_gallery_number_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedbib',
            index=models.Index(fields=['photo'], name='bib_photo_idx'),
        ),
        migrations.AddConstraint(
            model_name='detectedbib',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='bib_confidence_range'),
        ),
    ]
