# Generated by Django 5.2.17 on 2026-08-22 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_photo_optimized_file_photo_processed_at_and_more'),
        ('mapache_ai', '0002_bib_search_phase6'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedSearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('normalized_number', models.CharField(max_length=16)),
                ('consent_version', models.CharField(max_length=20)),
                ('consented_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('ERROR', 'Error')], max_length=12)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('face_results_count', models.PositiveIntegerField(default=0)),
                ('bib_results_count', models.PositiveIntegerField(default=0)),
                ('agreement_results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_search_sessions', to='galleries.gallery')),
            ],
            options={
                'verbose_name': 'sesión de búsqueda combinada',
                'verbose_name_plural': 'sesiones de búsqueda combinada',
                'indexes': [models.Index(fields=['gallery', 'expires_at'], name='combined_session_exp_idx')],
            },
        ),
    ]
