# Generated by Django 5.2.17 on 2026-08-23 02:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_alter_gallery_allow_gallery_download_and_more'),
        ('mapache_ai', '0003_combined_search_phase7'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibsearchsession',
            options={'verbose_name': 'sesión de búsqueda por número', 'verbose_name_plural': 'sesiones de búsqueda por número'},
        ),
        migrations.AlterModelOptions(
            name='faceembedding',
            options={'verbose_name': 'representación facial', 'verbose_name_plural': 'representaciones faciales'},
        ),
        migrations.AlterField(
            model_name='bibphotoanalysis',
            name='detected_count',
            field=models.PositiveIntegerField(default=0, verbose_name='dorsales detectados'),
        ),
        migrations.AlterField(
            model_name='bibphotoanalysis',
            name='error',
            field=models.CharField(blank=True, max_length=500, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='bibphotoanalysis',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_photo_analyses', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='bibphotoanalysis',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bib_analysis_state', to='galleries.photo', verbose_name='fotografía'),
        ),
        migrations.AlterField(
            model_name='bibphotoanalysis',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='procesada'),
        ),
        migrations.AlterField(
            model_name='bibphotoanalysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('INDEXING', 'Indexando'), ('READY', 'Lista'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='bibsearchsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
        migrations.AlterField(
            model_name='bibsearchsession',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='expira'),
        ),
        migrations.AlterField(
            model_name='bibsearchsession',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_search_sessions', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='bibsearchsession',
            name='normalized_number',
            field=models.CharField(max_length=16, verbose_name='número normalizado'),
        ),
        migrations.AlterField(
            model_name='bibsearchsession',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad de resultados'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='agreement_results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='resultados coincidentes'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='bib_results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='resultados por número'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='consent_version',
            field=models.CharField(max_length=20, verbose_name='versión del consentimiento'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='consented_at',
            field=models.DateTimeField(verbose_name='consentimiento otorgado'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='expira'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='face_results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='resultados por rostro'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_search_sessions', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='normalized_number',
            field=models.CharField(max_length=16, verbose_name='número normalizado'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad de resultados'),
        ),
        migrations.AlterField(
            model_name='combinedsearchsession',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('ERROR', 'Error')], max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='bounding_box',
            field=models.JSONField(verbose_name='recuadro del dorsal'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='confidence',
            field=models.FloatField(verbose_name='confianza'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_bibs', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='normalized_number',
            field=models.CharField(max_length=16, verbose_name='número normalizado'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_bibs', to='galleries.photo', verbose_name='fotografía'),
        ),
        migrations.AlterField(
            model_name='detectedbib',
            name='raw_text',
            field=models.CharField(max_length=64, verbose_name='texto detectado'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='bounding_box',
            field=models.JSONField(verbose_name='recuadro del rostro'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='confidence',
            field=models.FloatField(verbose_name='confianza'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=128, verbose_name='representación facial'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='face_index',
            field=models.PositiveIntegerField(verbose_name='número de rostro'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='galleries.photo', verbose_name='fotografía'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='consent_version',
            field=models.CharField(max_length=20, verbose_name='versión del consentimiento'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='consented_at',
            field=models.DateTimeField(verbose_name='consentimiento otorgado'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='expira'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_search_sessions', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad de resultados'),
        ),
        migrations.AlterField(
            model_name='facesearchsession',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('ERROR', 'Error')], max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_format',
            field=models.CharField(choices=[('NUMERIC', 'Numérico'), ('ALPHANUMERIC', 'Alfanumérico')], default='NUMERIC', max_length=16, verbose_name='formato del dorsal'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_indexed_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías con dorsales indexados'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_indexing_status',
            field=models.CharField(choices=[('DISABLED', 'Desactivado'), ('PENDING', 'Preparando'), ('INDEXING', 'Indexando'), ('READY', 'Listo'), ('ERROR', 'Error')], db_index=True, default='DISABLED', max_length=12, verbose_name='estado del índice de dorsales'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_last_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última indexación de dorsales'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_max_length',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='longitud máxima'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_min_length',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='longitud mínima'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_search_enabled',
            field=models.BooleanField(default=False, verbose_name='búsqueda por número'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='bib_total_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías de dorsales totales'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='activado'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='face_indexed_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías con índice facial'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='face_indexing_status',
            field=models.CharField(choices=[('DISABLED', 'Desactivado'), ('PENDING', 'Preparando'), ('INDEXING', 'Indexando'), ('READY', 'Listo'), ('ERROR', 'Error')], db_index=True, default='DISABLED', max_length=12, verbose_name='estado del índice facial'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='face_last_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última indexación facial'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='face_search_enabled',
            field=models.BooleanField(default=False, verbose_name='búsqueda por rostro'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='face_total_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías faciales totales'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='gallery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='indexed_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías indexadas'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='indexing_status',
            field=models.CharField(choices=[('DISABLED', 'Desactivado'), ('PENDING', 'Preparando'), ('INDEXING', 'Indexando'), ('READY', 'Listo'), ('ERROR', 'Error')], db_index=True, default='DISABLED', max_length=12, verbose_name='estado de indexación'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última indexación'),
        ),
        migrations.AlterField(
            model_name='galleryaisettings',
            name='total_photos',
            field=models.PositiveIntegerField(default=0, verbose_name='fotografías totales'),
        ),
        migrations.AlterField(
            model_name='photofaceindex',
            name='error',
            field=models.CharField(blank=True, max_length=500, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='photofaceindex',
            name='face_count',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad de rostros'),
        ),
        migrations.AlterField(
            model_name='photofaceindex',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_face_indexes', to='galleries.gallery', verbose_name='galería'),
        ),
        migrations.AlterField(
            model_name='photofaceindex',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='indexada'),
        ),
        migrations.AlterField(
            model_name='photofaceindex',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_index_state', to='galleries.photo', verbose_name='fotografía'),
        ),
        migrations.AlterField(
            model_name='photofaceindex',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('INDEXING', 'Indexando'), ('READY', 'Lista'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=12, verbose_name='estado'),
        ),
    ]
