# Generated by Django 5.2 for Mapache Studio.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Correo electrónico"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Teléfono"),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("SPORTS", "Fotografía deportiva"),
                            ("VIDEO", "Producción audiovisual"),
                            ("COMMERCIAL", "Fotografía comercial"),
                            ("DRONE", "Cobertura aérea"),
                            ("DIGITAL", "Contenido digital"),
                            ("PLATFORM", "Galerías y Mapache AI"),
                            ("OTHER", "Otro proyecto"),
                        ],
                        max_length=20,
                        verbose_name="Servicio",
                    ),
                ),
                ("message", models.TextField(max_length=3000, verbose_name="Mensaje")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recibido"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leído")),
            ],
            options={
                "verbose_name": "Consulta de contacto",
                "verbose_name_plural": "Consultas de contacto",
                "ordering": ["-created_at"],
            },
        ),
    ]
